### ISSUE TITLE
nacos-spring-cloud-discovery-example 运行异常

### ISSUE THREAD

**Issue by eastFu** [nacos-group/nacos-examples#14]
nacos-spring-cloud-discovery-example 例子运行报错， 什么原因造成的？

2019-03-20 19:14:15.018 ERROR 8052 --- [           main] o.s.c.a.n.registry.NacosServiceRegistry  : nacos registry, service-provider register failed...NacosRegistration{nacosDiscoveryProperties=NacosDiscoveryProperties{serverAddr='xx.xx.xx.xxx:8848', endpoint='', namespace='', logName='', service='service-provider', weight=1.0, clusterName='DEFAULT', metadata={}, registerEnabled=true, ip='192.168.8.78', networkInterface='', port=18080, secure=false, accessKey=', namingLoadCacheAtStart=false', secretKey=''}},

java.lang.IllegalStateException: failed to req API:/nacos/v1/ns/instance after all servers([xx.xx.xx.xxx:8848]) tried
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:335) ~[nacos-client-0.6.2.jar:na]

**Comment by 15036900300** [comment]
我也遇到了这个问题，网上有的人说是本机nacos没有单机模式启动的原因，但是我按照官网通过`sh startup.sh -m standalone`命令启动，也还是注册报上方异常，有的说通过`bash startup.sh -m standalone`启动，说sh和bash一些命令不一致，测试均不通过，当前还在研究中

**Comment by 15036900300** [comment]
我本机环境是mac，通过启动nacos单机模式，然后服务注册失败，异常如你所示，我讲nacos部署到服务器linux环境下后，通过`bash startup.sh -m standalone`命令启动后，服务注册成功，原因未详，查找中

**Comment by eastFu** [comment]
关于网上说的启动命令使用 bash/sh startup.sh -m standalone ,我都试过了， 都未成功，一顿纠结，我在尝试老版本  ~（* - *）~     
似乎 作者 不太关注这个仓库，o(︶︿︶)o 唉

**Comment by 15036900300** [comment]
@eastFu 我解决了，原因不详，你有微信或者qq没，我qq 459924498可以交流一下，微信ltr15036900300

**Comment by 15036900300** [comment]
@eastFu 不要下载源码，编译，直接下载编辑好的，启动，不要自己编译

**Comment by nkorange** [comment]
@eastFu 看下{user.home}/log/nacos/naming.log报错

**Comment by peterTao0506** [comment]
> nacos-spring-cloud-discovery-example 例子运行报错， 什么原因造成的？
> 
> 2019-03-20 19:14:15.018 ERROR 8052 --- [ main] o.s.c.a.n.registry.NacosServiceRegistry : nacos registry, service-provider register failed...NacosRegistration{nacosDiscoveryProperties=NacosDiscoveryProperties{serverAddr='xx.xx.xx.xxx:8848', endpoint='', namespace='', logName='', service='service-provider', weight=1.0, clusterName='DEFAULT', metadata={}, registerEnabled=true, ip='192.168.8.78', networkInterface='', port=18080, secure=false, accessKey=', namingLoadCacheAtStart=false', secretKey=''}},
> 
> java.lang.IllegalStateException: failed to req API:/nacos/v1/ns/instance after all servers([xx.xx.xx.xxx:8848]) tried
> at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:335) ~[nacos-client-0.6.2.jar:na]

请参考我提的issuer，我已解决服务注册的问题，看下是否能解决你的问题
